# Change these first
owner: vre-hub # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites: # add dashub, reana etc later on
  - name: VRE Notebook Service
    url: https://jhub-vre.cern.ch/
  - name: VRE Data Lake Service # add ports and url for auth and server
    url: https://vre-rucio-ui.cern.ch/
    __dangerous__disable_verify_peer: true # because of self singed cert
  - name: VRE FTS File Transfer Service
    url: https://fts3-pilot.cern.ch:8449/fts3/ftsmon/#/jobs?vo=escape&source_se=&dest_se=&time_window=6
    __dangerous__insecure: true
  - name: VRE IAM Service
    url: https://iam-escape.cloud.cnaf.infn.it/
  - name: VRE Monitoring Service
    url: http://monit-grafana-open.cern.ch/goto/ZqVveDC4k?orgId=16

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://vre-hub.github.io/images/logo.png
  name: VRE Service Status
  introTitle: "This is the service uptime status page of the Virtual Research Environment at CERN"
  introMessage: This status page shows **real-time** data of our services. Learn more about the VRE [**here**](https://vre-hub.github.io/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
# minutes are free for public repos and also for orgs?
# workflowSchedule:
#   graphs: "0 0 * * *"
#   responseTime: "0 23 * * *"
#   staticSite: "0 1 * * *"
#   summary: "0 0 * * *"
#   updateTemplate: "0 0 * * *"
#   updates: "0 3 * * *"
#   uptime: "* */12 * * *" # runs at every minute past every 12th hour
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
